# top level stuff you probably don't need to touch
#highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
#permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://gujavasc.github.io/
baseurl:
title: GUJavaSC
author: GUJavaSC
description: Personal blog and resume
avatar: logo.jpg
facebook: gujavasc
github: gujavasc # username
twitter: gujavasc
linkedin: gujavasc
slack: gujavasc   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
disqus: username
google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
